# Generated by Django 4.1.3 on 2022-12-16 01:34

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Descripción'),
        ),
    ]
