# Generated by Django 4.1.3 on 2022-12-08 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre')),
                ('Event_date', models.DateTimeField(verbose_name='Fecha del Evento')),
                ('place', models.CharField(max_length=120, verbose_name='Lugar')),
                ('description', models.TextField(blank=True, verbose_name='Descripcion')),
                ('mode', models.IntegerField(choices=[(1, 'Online'), (2, 'Presencial')], verbose_name='Modalidad')),
                ('cost', models.IntegerField(choices=[(1, 'Gratuito'), (2, 'De Pago')], verbose_name='Costo')),
                ('price', models.CharField(blank=True, max_length=10, verbose_name='Precio')),
            ],
        ),
    ]
