# Generated by Django 4.1.3 on 2022-12-13 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='event_category',
        ),
    ]
