# Generated by Django 4.1.3 on 2022-12-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='posts', verbose_name='Imagen'),
        ),
    ]
