# Generated by Django 4.1.3 on 2022-12-18 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo'),
        ),
    ]
