# Generated by Django 4.1.3 on 2022-12-18 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalizacion'),
        ),
    ]
